name: panda_test_app
description: "Panda test appp"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.2
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0

  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: # flutter pub run build_runner build --delete-conflicting-outputs
  flutter_gen_runner:

  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
   - assets/images/
